# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+UseParallelGC -Dfile.encoding=UTF-8
android.enableJetifier=true
android.nonFinalResIds=false
android.nonTransitiveRClass=false
android.useAndroidX=true
android.enableR8.fullMode=true

# AzadiTunnel Configuration
PSIPHON_CLIENT_VERSION=453
PSIPHON_PROPAGATION_CHANNEL_ID=07D1ACD69B3AC7A2
PSIPHON_SPONSOR_ID=EE0B7486ACAE75AA
PSIPHON_SERVER_ENTRY_SIGNATURE_PUBLIC_KEY=sHuUVTWaRyh5pZwy4UguSgkwmBe0EHtJJkoF5WrxmvA=
PSIPHON_SERVER_ENTRY_EXCHANGE_OBFUSCATION_KEY=DpXzloJk1Hw6aSzmKKky0xcahsEHubch81Mi6K0XMlU=
PSIPHON_REMOTE_SERVER_LIST_SIGNATURE_PUBLIC_KEY=MIICIDANBgkqhkiG9w0BAQEFAAOCAg0AMIICCAKCAgEAt7Ls+/39r+T6zNW7GiVpJfzq/xvL9SBH5rIFnk0RXYEYavax3WS6HOD35eTAqn8AniOwiH+DOkvgSKF2caqk/y1dfq47Pdymtwzp9ikpB1C5OfAysXzBiwVJlCdajBKvBZDerV1cMvRzCKvKwRmvDmHgphQQ7WfXIGbRbmmk6opMBh3roE42KcotLFtqp0RRwLtcBRNtCdsrVsjiI1Lqz/lH+T61sGjSjQ3CHMuZYSQJZo/KrvzgQXpkaCTdbObxHqb6/+i1qaVOfEsvjoiyzTxJADvSytVtcTjijhPEV6XskJVHE1Zgl+7rATr/pDQkw6DPCNBS1+Y6fy7GstZALQXwEDN/qhQI9kWkHijT8ns+i1vGg00Mk/6J75arLhqcodWsdeG/M/moWgqQAnlZAGVtJI1OgeF5fsPpXu4kctOfuZlGjVZXQNW34aOzm8r8S0eVZitPlbhcPiR4gT/aSMz/wd8lZlzZYsje/Jr8u/YtlwjjreZrGRmG8KMOzukV3lLmMppXFMvl4bxv6YFEmIuTsOhbLTwFgh7KYNjodLj/LsqRVfwz31PgWQFTEPICV7GCvgVlPRxnofqKSjgTWI4mxDhBpVcATvaoBl1L/6WLbFvBsoAUBItWwctO2xalKxF5szhGm8lccoc5MZr8kfE0uxMgsxz4er68iCID+rsCAQM=

# Updated to correct JSON structure for Go unmarshaling
PSIPHON_REMOTE_SERVER_LIST_URLS_JSON=[{"URL":"aHR0cHM6Ly9zMy5hbWF6b25hd3MuY29tL3BzaXBob24vd2ViL21qcjQtcDIzci1wdXdsL3NlcnZlcl9saXN0X2NvbXByZXNzZWQ="},{"URL":"aHR0cHM6Ly9zMy5hbWF6b25hd3MuY29tL3BzaXBob24vd2ViL3l0dG0temVpcy1wanpkL3NlcnZlcl9saXN0X2NvbXByZXNzZWQ="},{"URL":"aHR0cHM6Ly9zMy5hbWF6b25hd3MuY29tL3BzaXBob24vd2ViL2g4NjEtYXp2MC02cDk4L3NlcnZlcl9saXN0X2NvbXByZXNzZWQ="}]
PSIPHON_OBFUSCATED_SERVER_LIST_ROOT_URLS_JSON=[]
PSIPHON_FEEDBACK_UPLOAD_URLS_JSON=[]
PSIPHON_FEEDBACK_ENCRYPTION_PUBLIC_KEY=
PSIPHON_CONDUIT_COMPARTMENT_ID=DpXzloJk1Hw6aSzmKKky0xcahsEHubch81Mi6K0XMlU
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false
